### ISSUE TITLE
请问whisper模型在哪里更换，应该修改哪里的参数呢？

### ISSUE THREAD

**Issue by Swor-dart** [qinL-cdy/auto_ai_subtitle#1]
whisper我想用large的模型是把whisper_tool里的base改掉吗？具体这个模型在哪里啊？我之前用的是有UI界面的可以选择模型。还望大佬解答

**Comment by qinL-cdy** [comment]
要用large的话把这里的base改成large就行 [ model = whisper.load_model("base")](https://github.com/qinL-cdy/auto_ai_subtitle/blob/fad40988d5861a15ca8f65f2e7091bf1d1750cca/script/whisper_tool.py#L65C30-L65C30)
要用huggingface上的自定义模型的话，在配置文件的hf_model_path配置项填写模型地址
